encoding: utf-8

# SEO相关信息
title: Peter Blog
description: 思想的力量
keywords: Peter,Blog,BIOS,思考,阅读,哲学，心理学，历史，政治，投资，技术
author: Peter
footerText: 'Powered by My Mind'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
#domainUrl: 'http://blog.tmaize.net'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/192303

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: true

# 百度收录自动推送,不需要请设置为false
extBaidu: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: Dig into computer system
    url: https://blog.csdn.net/hgf1011
  # - title: Auuu Nya Blog
  #   url: http://mu1er.cn
  # - title: 春风十里
  #   url: https://www.geek-era.com
  # - title: 阿川的个人博客
  #   url: https://achuan.io
  # - title: 魏文成博客
  #   url: https://www.wwc.ren
  # - title: 06m
  #   url: https://www.06m.me
  # - title: 达达知识
  #   url: https://www.dadapush.com/
  # - title: 祈雨的博客
  #   url: https://wakzz.cn/
  # - title: hongCYu’s Blog
  #   url: https://hongcyu.cn/
  # - title: Sorryfu - 分享技术，记录生活
  #   url: https://sorryfu.top/
  # - title: 简单的人生笔记
  #   url: https://yoyling.com/
  # - title: oneNeko的博客
  #   url: https://blog.oneneko.com/